version: '3.8'

services:
  db:
    image: mysql:8.0.29

    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: clients

    ports:
      - "3310:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
    db_data:

